
drop table if exists neetcode150;

create table neetcode150
(
    pattern       text,
    title         text,
    difficulty_id integer,
    link          text
);

INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('array', 'Contains Duplicate', 1, 'https://leetcode.com/problems/contains-duplicate');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('array', 'Valid Anagram', 1, 'https://leetcode.com/problems/valid-anagram');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('array', 'Two Sum', 1, 'https://leetcode.com/problems/two-sum');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('array', 'Group Anagrams', 2, 'https://leetcode.com/problems/group-anagrams');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('array', 'Top K Frequent Elements', 2, 'https://leetcode.com/problems/top-k-frequent-elements');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('array', 'Product of Array Except Self', 2, 'https://leetcode.com/problems/product-of-array-except-self');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('array', 'Valid Sudoku', 2, 'https://leetcode.com/problems/valid-sudoku');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('array', 'Encode and Decode Strings', 2, 'https://leetcode.com/problems/encode-and-decode-strings');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Longest Consecutive Sequence', 3, 'https://leetcode.com/problems/longest-consecutive-sequence');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('two_pointers', 'Valid Palindrome', 1, 'https://leetcode.com/problems/valid-palindrome');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('two_pointers', 'Two Sum II', 2, 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('two_pointers', '3Sum', 2, 'https://leetcode.com/problems/3sum');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('two_pointers', 'Container with Most Water', 2, 'https://leetcode.com/problems/container-with-most-water');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('two_pointers', 'Trapping Rain Water', 3, 'https://leetcode.com/problems/trapping-rain-water');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('sliding_window', 'Best Time to Buy & Sell Stock', 1, 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('sliding_window', 'Longest Substring Without Repeating Characters', 2, 'https://leetcode.com/problems/longest-substring-without-repeating-characters');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('sliding_window', 'Longest Repeating Character Replacement', 2, 'https://leetcode.com/problems/longest-repeating-character-replacement');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('sliding_window', 'Permutation in String', 2, 'https://leetcode.com/problems/permutation-in-string');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('sliding_window', 'Minimum Window Substring', 3, 'https://leetcode.com/problems/minimum-window-substring');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('sliding_window', 'Sliding Window Maximum', 3, 'https://leetcode.com/problems/sliding-window-maximum');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('stack', 'Valid Parentheses', 1, 'https://leetcode.com/problems/valid-parentheses');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('stack', 'Min Stack', 2, 'https://leetcode.com/problems/min-stack');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('stack', 'Evaluate Reverse Polish Notation', 2, 'https://leetcode.com/problems/evaluate-reverse-polish-notation');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('stack', 'Generate Parentheses', 2, 'https://leetcode.com/problems/generate-parentheses');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('stack', 'Daily Temperatures', 2, 'https://leetcode.com/problems/daily-temperatures');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('stack', 'Car Fleet', 2, 'https://leetcode.com/problems/car-fleet');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('stack', 'Largest Rectangle in Histogram', 3, 'https://leetcode.com/problems/largest-rectangle-in-histogram');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('binary_search', 'Binary Search', 1, 'https://leetcode.com/problems/binary-search');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('binary_search', 'Search a 2D Matrix', 2, 'https://leetcode.com/problems/search-a-2d-matrix');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('binary_search', 'Koko Eating Bananas', 2, 'https://leetcode.com/problems/koko-eating-bananas');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('binary_search', 'Search Rotated Sorted Array', 2, 'https://leetcode.com/problems/search-in-rotated-sorted-array');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('binary_search', 'Find Minimum in Rotated Sorted Array', 2, 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('binary_search', 'Time Based Key-Value Store', 2, 'https://leetcode.com/problems/time-based-key-value-store');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('binary_search', 'Find Median of Two Sorted Arrays', 3, 'https://leetcode.com/problems/median-of-two-sorted-arrays');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Reverse Linked List', 1, 'https://leetcode.com/problems/reverse-linked-list');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Merge Two Linked Lists', 1, 'https://leetcode.com/problems/merge-two-sorted-lists');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Reorder List', 2, 'https://leetcode.com/problems/reorder-list');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Remove Nth Node from End of List', 2, 'https://leetcode.com/problems/remove-nth-node-from-end-of-list');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Copy List with Random Pointer', 2, 'https://leetcode.com/problems/copy-list-with-random-pointer');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Add Two Numbers', 2, 'https://leetcode.com/problems/add-two-numbers');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Linked List Cycle', 1, 'https://leetcode.com/problems/linked-list-cycle');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Find the Duplicate Number', 2, 'https://leetcode.com/problems/find-the-duplicate-number');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'LRU Cache', 2, 'https://leetcode.com/problems/lru-cache');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Merge K Sorted Lists', 3, 'https://leetcode.com/problems/merge-k-sorted-lists');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('linked_list', 'Reverse Nodes in K-Group', 3, 'https://leetcode.com/problems/reverse-nodes-in-k-group');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Invert Binary Tree', 1, 'https://leetcode.com/problems/invert-binary-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Maximum Depth of Binary Tree', 1, 'https://leetcode.com/problems/maximum-depth-of-binary-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Diameter of a Binary Tree', 1, 'https://leetcode.com/problems/diameter-of-binary-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Balanced Binary Tree', 1, 'https://leetcode.com/problems/balanced-binary-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Same Tree', 1, 'https://leetcode.com/problems/same-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Subtree of Another Tree', 1, 'https://leetcode.com/problems/subtree-of-another-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Lowest Common Ancestor of a BST', 1, 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Binary Tree Level Order Traversal', 2, 'https://leetcode.com/problems/binary-tree-level-order-traversal');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Binary Tree Right Side View', 2, 'https://leetcode.com/problems/binary-tree-right-side-view');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Count Good Nodes in a Binary Tree', 2, 'https://leetcode.com/problems/count-good-nodes-in-binary-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Validate Binary Search Tree', 2, 'https://leetcode.com/problems/validate-binary-search-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Kth Smallest Element in a BST', 2, 'https://leetcode.com/problems/kth-smallest-element-in-a-bst');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Construct Tree from Preorder and Inorder Traversal', 2, 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Binary Tree Max Path Sum', 3, 'https://leetcode.com/problems/binary-tree-maximum-path-sum');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('tree', 'Serialize and Deserialize Binary Tree', 3, 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('trie', 'Implement Trie', 2, 'https://leetcode.com/problems/implement-trie-prefix-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('trie', 'Design Add and Search Word Data Structure', 2, 'https://leetcode.com/problems/design-add-and-search-words-data-structure');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('trie', 'Word Search II', 3, 'https://leetcode.com/problems/word-search-ii');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('heap_priority_queue', 'Kth Largest Element in a Stream', 1, 'https://leetcode.com/problems/kth-largest-element-in-a-stream');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('heap_priority_queue', 'Last Stone Weight', 1, 'https://leetcode.com/problems/last-stone-weight');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('heap_priority_queue', 'K Closest Points to Origin', 2, 'https://leetcode.com/problems/k-closest-points-to-origin');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('heap_priority_queue', 'Kth Largest Element in an Array', 2, 'https://leetcode.com/problems/kth-largest-element-in-an-array');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('heap_priority_queue', 'Task Scheduler', 2, 'https://leetcode.com/problems/task-scheduler');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('heap_priority_queue', 'Design Twitter', 2, 'https://leetcode.com/problems/design-twitter');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('heap_priority_queue', 'Find Median from Data Stream', 3, 'https://leetcode.com/problems/find-median-from-data-stream');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'Subsets', 2, 'https://leetcode.com/problems/subsets');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'Combination Sum', 2, 'https://leetcode.com/problems/combination-sum');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'Permutations', 2, 'https://leetcode.com/problems/permutations');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'Subsets II', 2, 'https://leetcode.com/problems/subsets-ii');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'Combination Sum II', 2, 'https://leetcode.com/problems/combination-sum-ii');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'Word Search', 2, 'https://leetcode.com/problems/word-search');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'Palindrome Partitioning', 2, 'https://leetcode.com/problems/palindrome-partitioning');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'Letter Combinations of a Phone Number', 2, 'https://leetcode.com/problems/letter-combinations-of-a-phone-number');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('backtracking', 'N-Queens', 3, 'https://leetcode.com/problems/n-queens');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Number of Islands', 2, 'https://leetcode.com/problems/number-of-islands');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Clone Graph', 2, 'https://leetcode.com/problems/clone-graph');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Max Area of Island', 2, 'https://leetcode.com/problems/max-area-of-island');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Pacific Atlantic Waterflow', 2, 'https://leetcode.com/problems/pacific-atlantic-water-flow');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Surrounded Regions', 2, 'https://leetcode.com/problems/surrounded-regions');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Rotting Oranges', 2, 'https://leetcode.com/problems/rotting-oranges');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Walls and Gates', 2, 'https://leetcode.com/problems/walls-and-gates');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Course Schedule', 2, 'https://leetcode.com/problems/course-schedule');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Course Schedule II', 2, 'https://leetcode.com/problems/course-schedule-ii');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Redundant Connection', 2, 'https://leetcode.com/problems/redundant-connection');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Number of Connected Components in Graph', 2, 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Graph Valid Tree', 2, 'https://leetcode.com/problems/graph-valid-tree');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('graph', 'Word Ladder', 3, 'https://leetcode.com/problems/word-ladder');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('advanced_graph', 'Reconstruct Itinerary', 3, 'https://leetcode.com/problems/reconstruct-itinerary');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('advanced_graph', 'Min Cost to Connect all Points', 2, 'https://leetcode.com/problems/min-cost-to-connect-all-points');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('advanced_graph', 'Network Delay Time', 2, 'https://leetcode.com/problems/network-delay-time');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('advanced_graph', 'Swim in Rising Water', 3, 'https://leetcode.com/problems/swim-in-rising-water');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('advanced_graph', 'Alien Dictionary', 3, 'https://leetcode.com/problems/alien-dictionary');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('advanced_graph', 'Cheapest Flights with K Stops', 2, 'https://leetcode.com/problems/cheapest-flights-within-k-stops');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Climbing Stairs', 1, 'https://leetcode.com/problems/climbing-stairs');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Min Cost Climbing Stairs', 1, 'https://leetcode.com/problems/min-cost-climbing-stairs');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'House Robber', 2, 'https://leetcode.com/problems/house-robber');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'House Robber II', 2, 'https://leetcode.com/problems/house-robber-ii');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Longest Palindroming Substring', 2, 'https://leetcode.com/problems/longest-palindromic-substring');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Palindrome Substrings', 2, 'https://leetcode.com/problems/palindromic-substrings');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Decode Ways', 2, 'https://leetcode.com/problems/decode-ways');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Coin Change', 2, 'https://leetcode.com/problems/coin-change');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Maximum Product Subarray', 2, 'https://leetcode.com/problems/maximum-product-subarray');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Word Break', 2, 'https://leetcode.com/problems/word-break');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Longest Increasing Subsequence', 2, 'https://leetcode.com/problems/longest-increasing-subsequence');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('1d_dynamic_programming', 'Partition Equal Subset Sum', 2, 'https://leetcode.com/problems/partition-equal-subset-sum');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Unique Paths', 2, 'https://leetcode.com/problems/unique-paths');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Longest Common Subsequence', 2, 'https://leetcode.com/problems/longest-common-subsequence');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Best Time to Buy/Sell Stock With Cooldown', 2, 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Coin Change II', 2, 'https://leetcode.com/problems/coin-change-2');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Target SUm', 2, 'https://leetcode.com/problems/target-sum');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Interleaving String', 2, 'https://leetcode.com/problems/interleaving-string');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Longest Increasing Path in a Matrix', 3, 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Distinct Subsequences', 3, 'https://leetcode.com/problems/distinct-subsequences');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Edit Distance', 3, 'https://leetcode.com/problems/edit-distance');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Burst Balloons', 3, 'https://leetcode.com/problems/burst-balloons');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('2d_dynamic_programming', 'Regular Expression Matching', 3, 'https://leetcode.com/problems/regular-expression-matching');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('greedy', 'Maximum Subarray', 2, 'https://leetcode.com/problems/maximum-subarray');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('greedy', 'Jump Game', 2, 'https://leetcode.com/problems/jump-game');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('greedy', 'Jump Game II', 2, 'https://leetcode.com/problems/jump-game-ii');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('greedy', 'Gas Station', 2, 'https://leetcode.com/problems/gas-station');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('greedy', 'Hand of Straights', 2, 'https://leetcode.com/problems/hand-of-straights');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('greedy', 'Merge Triplets to Form Target Triplet', 2, 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('greedy', 'Partition Labels', 2, 'https://leetcode.com/problems/partition-labels');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('greedy', 'Valid Parenthesis String', 2, 'https://leetcode.com/problems/valid-parenthesis-string');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('interval', 'Insert Interval', 2, 'https://leetcode.com/problems/insert-interval');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('interval', 'Merge Intervals', 2, 'https://leetcode.com/problems/merge-intervals');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('interval', 'Non-Overlapping Intervals', 2, 'https://leetcode.com/problems/non-overlapping-intervals');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('interval', 'Meeting Rooms', 1, 'https://leetcode.com/problems/meeting-rooms');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('interval', 'Meeting Rooms II', 2, 'https://leetcode.com/problems/meeting-rooms-ii');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('interval', 'Minimum Interval to Include Each Query', 3, 'https://leetcode.com/problems/minimum-interval-to-include-each-query');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('math', 'Rotate Image', 2, 'https://leetcode.com/problems/rotate-image');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('math', 'Spiral Matrix', 2, 'https://leetcode.com/problems/spiral-matrix');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('math', 'Set Matrix Zeroes', 2, 'https://leetcode.com/problems/set-matrix-zeroes');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('math', 'Happy Number', 1, 'https://leetcode.com/problems/happy-number');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('math', 'Plus One', 1, 'https://leetcode.com/problems/plus-one');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('math', 'Pow(x, n)', 2, 'https://leetcode.com/problems/powx-n');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('math', 'Multiply Strings', 2, 'https://leetcode.com/problems/multiply-strings');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('math', 'Detect Squares', 2, 'https://leetcode.com/problems/detect-squares');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('bit_manipulation', 'Single Number', 1, 'https://leetcode.com/problems/single-number');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('bit_manipulation', 'Number of 1 Bits', 1, 'https://leetcode.com/problems/number-of-1-bits');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('bit_manipulation', 'Counting Bits', 1, 'https://leetcode.com/problems/counting-bits');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('bit_manipulation', 'Reverse Bits', 1, 'https://leetcode.com/problems/reverse-bits');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('bit_manipulation', 'Missing Number', 1, 'https://leetcode.com/problems/missing-number');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('bit_manipulation', 'Sum of Two Integers', 2, 'https://leetcode.com/problems/sum-of-two-integers');
INSERT INTO neetcode150 (pattern, title, difficulty_id, link) VALUES ('bit_manipulation', 'Reverse Integer', 2, 'https://leetcode.com/problems/reverse-integer');
